WIP: import relay-reborn
signalwire/signalwire-ruby-old pull request #13
Opened 2019-07-13 13:12 UTC by lpradovera

Do not merge!

2019-07-15 18:36 UTC, bryanrite requested changes
Couple of suggestions, mostly just clean up examples, issue with space_url and host... but overall, looks great! 👍

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/inbound_consumer.rb
> +    call.play [{ "type": 'tts', "params": { "text": 'the quick brown fox jumps over the lazy dog', "language": 'en-US', "gender": 'male' } }]
Can we replace with `playTTS`, want the examples to be simple and approachable.

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/inbound_dial.rb
> +    call.play [{ "type": 'tts', "params": { "text": 'connecting you to the clock service', "language": 'en-US', "gender": 'male' } }]
Same comment as above, simplify by using `playTTS`

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/low_level.rb
> +# frozen_string_literal: true
Remove this file, doesn't seem to do anything different than above examples>

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/outbound_collect.rb
> +    collect_params = { "initial_timeout": 10.0, "digits": { "max": 1, "digit_timeout": 5.0 } }
`prompt_params`

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/outbound_collect.rb
> +    call.dial
Join new_call and dial into single line, simplify example.

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/outbound_collect.rb
> +    result = call.prompt( collect_params, play_params)
use promptTTS

2019-07-15 18:36 UTC, bryanrite commented on examples/relay/outbound_collect.rb
> +    call.play [{ "type": 'tts', "params": { "text": "You ordered #{result.result} hamburgers. Thank you!", "language": 'en-US', "gender": 'male' } }]
use playTTS

2019-07-15 18:36 UTC, bryanrite commented on lib/signalwire/blade/connection.rb
> +      @url = @options.fetch(:url, 'wss://relay.signalwire.com')
I believe the option should be `host`, not `url`, but its not exposed to the end-user yet, so you can make a note for next version to change.

Also, host would just be `relay.signalwire.com`, they wouldn't specify `wss://`... this is especially important for the Tasks, since they would be `https://HOST`

2019-07-15 18:36 UTC, bryanrite commented on lib/signalwire/logger.rb
> +          logger.level = ENV.fetch('SIGNALWIRE_LOG_LEVEL', ::Logger::DEBUG)
Do we want debug to be the default?

2019-07-15 18:36 UTC, bryanrite commented on lib/signalwire/relay/client.rb
> +    def initialize(project:, token:, signalwire_space_url: nil)
In earlier comment, i think this should be `host` instead of `signalwire_space_url`...

2019-07-15 18:36 UTC, bryanrite commented on lib/signalwire/relay/constants.rb
> +  DEFAULT_URL = 'wss://relay.signalwire.com'
Same comments as above, keep host and protocol separate since Tasks will use a non WSS endpoint.

2019-07-15 18:36 UTC, bryanrite commented on lib/signalwire/relay/consumer.rb
> +    def initialize(project: nil, token: nil, space_url: nil)
same as above, space_url is gone, replace with host.

2019-07-15 18:36 UTC, bryanrite commented on lib/signalwire/version.rb
> +  VERSION = '2.0.0'
```suggestion
  VERSION = '2.0.0-rc.1'
```

2019-07-16 09:41 UTC, lpradovera commented on examples/relay/outbound_collect.rb
> +    collect_params = { "initial_timeout": 10.0, "digits": { "max": 1, "digit_timeout": 5.0 } }
In this case the input part is always named `collect` so this is correct.

2019-07-16 15:31 UTC, merged