WIP: Fax Relay API
signalwire/signalwire-ruby-old pull request #18
Opened 2019-07-17 15:44 UTC by lpradovera

2019-07-18 09:39 UTC, lpradovera commented
@bryanrite please review.

2019-07-18 16:22 UTC, bryanrite submitted a review, later dismissed
Looks great!

2019-07-18 16:22 UTC, bryanrite commented on examples/relay/fax/fax_receive.rb
> +    logger.debug "Received a fax: #{fax_result.document} that is #{fax_result.pages} pages long"
```suggestion
    logger.debug "Received a fax: #{fax_result.document} that is #{fax_result.pages} pages long."
```

2019-07-18 16:22 UTC, bryanrite submitted a review, later dismissed

2019-07-19 18:43 UTC, bryanrite requested changes

2019-07-19 18:43 UTC, bryanrite commented on examples/relay/fax/fax_send.rb
> +    call.fax_send("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf")
```suggestion
    call.fax_send(document: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf")
```

2019-07-19 18:43 UTC, bryanrite approved these changes

2019-07-19 18:47 UTC, merged