WIP: Feature/messaging
signalwire/signalwire-ruby-old pull request #24
Opened 2019-07-26 14:17 UTC by lpradovera

2019-07-26 15:23 UTC, lpradovera commented
@bryanrite please start taking a look. I could not test reception, everything looks good on the wire but messages don't show up, either in Relay or the SW dashboard.

2019-07-26 17:17 UTC, bryanrite requested changes
Couple small changes, but looking good so far!

2019-07-26 17:17 UTC, bryanrite commented on examples/relay/messaging/messaging_receive.rb
> +  def on_message(message)
This looks incorrect, RCI uses `onIncomingMessage` and `onMessageStateChange`

2019-07-26 17:17 UTC, bryanrite commented on lib/signalwire/relay/messaging.rb
> +        body = params.delete(:body)
https://github.com/signalwire/signalwire-ruby/pull/24/files#diff-e098efa94866bd8afc980b042607487fR21-R28

This section is a bit weird. You remove from params, set payload equal to params, then re-add to payload, then readd payload into params, seems like unnecessary juggling... not a big deal, but looks weird.

I would also remove the error checking. Error checking is done on the server side, don't need to enforce it in the client. We might add a feature like a campaign, or AI integration, that selects body/media from the server side, in which case this validation is invalid.

2019-07-28 04:47 UTC, lpradovera commented
@bryanrite ready for review.

2019-07-29 16:29 UTC, bryanrite approved these changes
🚀 🚀

2019-07-29 16:31 UTC, merged