Correctly set call peer
signalwire/signalwire-ruby-old pull request #30
Opened 2019-07-31 21:52 UTC by lpradovera

2019-07-31 21:59 UTC, bryanrite requested changes
Small typo!

2019-07-31 21:59 UTC, bryanrite commented on spec/signalwire/relay/calling/call_spec.rb
> +    fit 'sets the peer and fires the event' do
```suggestion
    it 'sets the peer and fires the event' do
```

2019-07-31 22:02 UTC, bryanrite submitted a review, later dismissed

2019-07-31 22:03 UTC, bryanrite requested changes
Add a Fix changelog entry please.

2019-08-01 16:33 UTC, lpradovera commented
@bryanrite entry added.

2019-08-01 16:37 UTC, bryanrite submitted a review, later dismissed

2019-08-01 16:41 UTC, bryanrite approved these changes

2019-08-01 16:42 UTC, merged