Working Fax REST API
signalwire/signalwire-ruby-old pull request #4
Opened 2019-01-04 16:57 UTC by lpradovera

2019-01-04 18:49 UTC, bryanrite requested changes
The monkey patching looks great, but lets remove all the unnecessary and bits from the cassettes, and make them more general (`example` vs your personal space, etc), I'd rather keep those more bare bones.

2019-01-04 18:49 UTC, bryanrite commented on spec/spec_helper.rb
> +    # recommended. For more details, see:
Revert this.

2019-01-05 11:07 UTC, lpradovera commented
Should be GTG now.

2019-01-06 22:01 UTC, bryanrite requested changes
Few more changes, mostly just formatting and cleaning up the cassettes.

Thanks @lpradovera !

2019-01-06 22:01 UTC, bryanrite commented on spec/signalwire/rest/integration_spec.rb
> +          media_url: 'http://www.orimi.com/pdf-test.pdf'
Can we use `https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf` as the test URL and fake phone numbers, I would prefer the w3 link than a random Russian tea website :)

2019-01-06 22:01 UTC, bryanrite commented on spec/vcr_cassettes/accounts.yml
> +---
The cassettes still need a lot of pieces removed... I'll comment below for this one, but all of them should have the same scrubbing applied:

2019-01-06 22:01 UTC, bryanrite commented on spec/vcr_cassettes/accounts.yml
> +    headers:
Should be able to remove almost all of these headers since that is being sent server side and we're not validating that here.

2019-01-06 22:01 UTC, bryanrite commented on spec/vcr_cassettes/accounts.yml
> +    headers:
Remove `Server`, `X-Ratelimit-*`, `Content-Security-Policy`, and any other headers that are not required by the test suite to run... perhaps we just need the body?

2019-01-06 22:01 UTC, bryanrite commented on lib/signalwire/sdk/twilio_set_fax.rb
> +          'Signalwire Space URL is not configured. Enter your Signalwire Space domain via the '\
Replace with SignalWire (with the capital W) please (in the string, not the namespace)

2019-01-06 22:01 UTC, bryanrite commented on lib/signalwire/sdk/twilio_set_fax.rb
> +            @solution = {sid: sid, }
Hanging `,` here and inconsistent spacing.

2019-01-07 15:48 UTC, lpradovera commented
Cleaned and squashed to erase history.

2019-01-07 22:53 UTC, bryanrite submitted a review, later dismissed

2019-01-07 22:53 UTC, bryanrite commented
LGTM!

2019-01-11 16:23 UTC, lpradovera commented
@bryanrite no idea why it's not letting me merge. Please re-approve when you have time.

2019-01-11 17:26 UTC, bryanrite approved these changes

2019-01-12 16:38 UTC, merged